repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: pylint
        name: Run pylint locally
        entry: python -m pylint
        language: system
        types: [python]
        args: ["--disable=missing-module-docstring,missing-function-docstring"]
