services:
  - type: web
    name: chartfly-backend
    runtime: python
    plan: starter # or 'free' if you're still testing
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: OTHER_ENV_VAR
        sync: false