services:
  - type: web
    name: chartfly-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    buildFilter:
      paths:
        - main.py
        - control_console/**
        - requirements.txt
        - templates/**
        - static/admin/shared/**
        - static/admin/user-management/**
        - static/admin/api-keys/**
        - static/admin/market-holidays/**
        - static/css/**
        - static/images/**
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
